const whiteVin = [
  {
    name: 'Оливье Трикон Шабли',
    country: 'Франция',
    region: 'Бургундия',
    manufaktur: 'Оливье Трикон',
    sort: 'Шардоне',
  },
  {
    name: "Люньи Л'Аурор Бургонь Шардоне",
    country: 'Франция',
    region: 'Бургундия',
    manufaktur: 'Люньи Ляурор',
    sort: 'Шардоне',
  },
  {
    name: 'Шато де Пареншер Блан',
    country: 'Франция',
    region: 'Бордо',
    manufaktur: 'Шато де Параншер',
    sort: '55 Совиньен Блан, 30 Сомильон, 15 Мюскадель',
  },
  {
    name: 'Куатро Райас, 4Р Вердехо',
    country: 'Испания',
    region: 'Кастилия и Леон',
    manufaktur: 'Куатро Райас',
    sort: 'Вердехо',
  },
  {
    name: 'Вайнгур Лет, Дуэт Рислинг энд Вельтлинер',
    country: 'Астрия',
    region: 'Нижняя Австрия',
    manufaktur: 'Лет',
    sort: 'Грюнер Вельтлинер и Рислинг',
  },
  {
    name: '',
    country: '',
    region: '',
    manufaktur: '',
    sort: '',
  },
  {
    name: '',
    country: '',
    region: '',
    manufaktur: '',
    sort: '',
  },
  {
    name: '',
    country: '',
    region: '',
    manufaktur: '',
    sort: '',
  },
  {
    name: '',
    country: '',
    region: '',
    manufaktur: '',
    sort: '',
  },
  {
    name: '',
    country: '',
    region: '',
    manufaktur: '',
    sort: '',
  },
]
